# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180320_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
