# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20180320_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created'], 'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
    ]
