# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20180320_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(default='', upload_to='notes_img'),
            preserve_default=False,
        ),
    ]
